<style  TYPE="text/css">
<!--
body { font-family: verdana; } 
pre { font-family: courier;  font-size: 0.7em;}
span.Symbol { color: #00FFFF; } 
span.String { color: #FF00FF; }
span.HexNumber { color: #FF00FF; } 
span.Comment { color: #F4F889; }
span.Keyword { color: #FF8000; font-weight: bold; }
span.Directive { color: #CC3333; font-weight: bold; }
span.Identifier { color: #CCCCCC; }
span.Number { color: #FFFF00; }
-->
</style>
